### ISSUE TITLE
The said issues.

### ISSUE THREAD

**Issue by janmarinka** [0P3N50URC3-F0R3V3R/SBRW-COMPILED#2]
Hello,
thank you for reaching back to me,
we can communicate through the issue tab. Let me show you what I´d love to change. And couldnt find in the database "product".
![image](https://user-images.githubusercontent.com/56171849/158036921-3fa9c974-36f3-4b62-85e7-0f54d2a5955c.png)
My database for Car Slots is set as CASH not _NS and the price is completely different yet it shows 100 SB and if i have speedboost it still wont purchase. 
![image](https://user-images.githubusercontent.com/56171849/158036945-15543fcd-a12e-4452-baa0-0561875d7b1b.png)
Next, I wanted to ask if its possible to change the 0 SB on the Mysterypack? this can be abused a lot, so if i could disable the Mystery Pack for SB and keep only the one for cash, or if I could set its price to more speedboost it would be wonderful. I checked the product database that item is not found at all. 

Thanks for responding,
Jan.

**Comment by janmarinka** [comment]
Additionally, where can I change the link that your browser leads to once you click top up? This is the current link and I´d like to make it lead to a site where it says you cant purchase speedboost.
![image](https://user-images.githubusercontent.com/56171849/158037175-209e8918-06f2-4cac-a5c3-2c2c0857756b.png)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Hm you said you added two new features not some errors XD but whatever, lets check it... so. I never fixed the webshop imho it is not working and not part of the code neither i was unable to activate/repair news... Also the help system is broken too.

YOU dont need carslots, since every player has maximal carslots, also carslots item is broken so i would not even bother....
i have to mention that the carslots is in the products also. EVERYTHING is in the profucts that purchasable so are this. Also it is not working, that is why by default everyone has maximal slots... 

IF you change CASH to _NG and backwards, the buttons will not change ingame, but the price will alter... so if you are changing a price to CASH instead of _NG ingame it will stay as boost but it will use money...(The buttonsa re needs to be modded to change that too wich i can and will not help there are modder sites for that purpose...)

You can disable the mystery packs and in fact every item in game by editing the Products -> Enabled column, 0 if off 1 is on, you can do this with every item in the shop and cars and drops and such..... The database itself is pretty self explanatory, you can set prices, and such. The packs is in tha last entries approximately in the list...

Also you can change the column CASH to _NG to make some product to use Boost instead of money... If you need, you can use the clean database in this repacks just download the NOT portable one from the relases and use the clean SQL file from that. Those has items with BOOST.

Everything is puchasable ingame so never bothered with the store, that is not part of the source and i dont know how to change it i guess it would be needed to change it on server side.... for this check around the SBRW githubs but so far afaik they dont have store neither...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
![image](https://user-images.githubusercontent.com/94479523/158037516-d8167c96-c049-43f1-9049-30eea9bba402.png)
This is the car slots item in product database

**Comment by janmarinka** [comment]
Towards the shop, its okay. The carslots we can ignore as well. Im using the database from your portable server. Nowhere I could find, the mystery cards to enable or disable, i browsed thru the entire products category.

**Comment by janmarinka** [comment]
Also I got helpguide to work, its just a bunch of html

**Comment by 0P3N50URC3-F0R3V3R** [comment]
What is wrong with theese entries? If there would be not in the product you would be not able to see them....

![image](https://user-images.githubusercontent.com/94479523/158037682-bf75b9e6-7a55-41f1-b606-d942de2af557.png)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
From 7264 to 7373 is all card packs lot of them are bugged but you need to figure it out wich is good and wich is bad...

**Comment by janmarinka** [comment]
Holy shoot how, they are not in my product category. I was able to edit and enable booster items from there, but never mystery packs, they just dont show up

**Comment by 0P3N50URC3-F0R3V3R** [comment]
WHat editor you use for the DB?

**Comment by janmarinka** [comment]
Probably using a stupid sql editor xD

**Comment by 0P3N50URC3-F0R3V3R** [comment]
In navicat you need to turn the pages at the lower right, there is a pagination, or turn off limitation, they will be there. you jjust need to turn the pages, or as i said turn off the record limit

**Comment by janmarinka** [comment]
Right, im using some generic trash Sql editor from mysql. Its the only thing i got on my vps, thats probably why so many things dont show up

**Comment by janmarinka** [comment]
Btw, tommorow I can help you get news and helpguide working if you want, i got both of them working

**Comment by 0P3N50URC3-F0R3V3R** [comment]
If they would not be in the DB then in game they would not show up so use Navicat or HeidiSQL

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> Btw, tommorow I can help you get news and helpguide working if you want, i got both of them working

OFC if you can make a short tutorial for it it is welcome, i would create a file in the project to be in the relases :D i would thank that very much :D

**Comment by janmarinka** [comment]
Right! I'll try that tommorow. This one is so trash it cant even enable/ disable races. Throws an error, shoves in invalid sql entries. Thanks

**Comment by 0P3N50URC3-F0R3V3R** [comment]
OKay then :D try it and check the link above there are plenty of free MYSQL editors; that are more than good :D 

For the news please open an other issue :D

**Comment by janmarinka** [comment]
Btw before I had other two issues, of cars not spawning and first race not having bots, but then i realized it was just a mod in the htdocs folder in the portable server disabling it :D

**Comment by janmarinka** [comment]
Because the modded non portable had it working with the MW nexus interface :)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> Btw before I had other two issues, of cars not spawning and first race not having bots, but then i realized it was just a mod in the htdocs folder in the portable server disabling it :D

Because the modded non portable had it working with the MW nexus interface :)

Yes the mods are there just for showing how to mod the game, also you can open and edit the .mods files with a winrar.

**Comment by janmarinka** [comment]
What i tried to do with my setup was to make it as vanilla as possible, i changed the logos everywhere to the original need for speed world logos. Im using the custom launcher as well because it gives the game need for speed world logo on the startup. However maybe 1 more issue that could be improved is the out of resolution Quicklime games logo xD

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I cannot help with GFX and Textures i am struggling with that too,(IDK how to create gfx, i took the original logo from the beta client, and also edited the custom luncher in Visual studio) also i would not recommend vanilla, most of the races are bugged....my modpack is fixes them also makes possible to go to team escape with bots, in vanilla there are only muliplayer Team Escapes...

**Comment by 0P3N50URC3-F0R3V3R** [comment]
The logo is in BootFlow.gfx, but the intro video, i do not know...

**Comment by janmarinka** [comment]
Maybe we could take the quicklime anim from the current SBRW client?

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Perhaps, you can check their mods when you are downloading their mod files.... but i dont know wich file is that one :D

**Comment by janmarinka** [comment]
Since the animation is fixed there, i guess it should be possible

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Perhaps, you can check their mods when you are downloading their mod files.... but i dont know wich file is that one :D You need to use their launcher tho to get those files, and you need them extracted from cash(since they mod files are protected, but at start the game extracts it to your caches...)

**Comment by janmarinka** [comment]
Yeah I see. Maybe the quicklime anim could be extracted

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Yes it can be if it is there the mods will be extracted to :

.data 

But you need to figure it out wich server, since they gget a hash foldername instead of a normal name

**Comment by 0P3N50URC3-F0R3V3R** [comment]
So? Any news how to use the news?

**Comment by janmarinka** [comment]
Currently making a tutorial so news can be universal. Right now they work only on my machine, due to programmed stuff. I wanted to ask. Where did you grab that Launch anim? I cant find the old one anywhere :( i just want to fix the limegames logo. Btw thank you!!! The card pack trick worked flawlessly. Since car slots is at max i dont need that either. I just really wonder how could i fix that anim.. thanks!!

**Comment by janmarinka** [comment]
UPDATE: BEen fighting it for HOURS and im getting so frustruated i cant get it to change idk how you did it

**Comment by janmarinka** [comment]
PS: I have the correct file from 2014 now but I CANT GET IT TO CHANGE

**Comment by janmarinka** [comment]
[BootFlow.zip](https://github.com/0P3N50URC3-F0R3V3R/SBRW-COMPILED/files/8273883/BootFlow.zip)
This is hours of extensive research... But still cant get it to display properly.

**Comment by janmarinka** [comment]
or well, display at all for that matter.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
TBH i never did grabbed it intentionally, so i do not know wich file is that.... also it might be possible that is in bootflow.gfx...? idk...

**Comment by janmarinka** [comment]
How can I edit .gfx files?

**Comment by janmarinka** [comment]
I'd really love to get this working when i spent hours xD tryna find a og one

**Comment by 0P3N50URC3-F0R3V3R** [comment]
> How can I edit .gfx files?

-.-' 

As i said in this thread before if you know how to edit gfx files, share with me since i dont know either,,,

**Comment by janmarinka** [comment]
How did you update the logo bootscreen,

**Comment by janmarinka** [comment]
I just cant get it to update. But dont worry, we can team to figure this out, and we will at the end

**Comment by janmarinka** [comment]
I know a owner of a sbrw server so I just asked him, possibly he can help.

**Comment by janmarinka** [comment]
I think i know the solution. Tommorow i'll do this

**Comment by 0P3N50URC3-F0R3V3R** [comment]
You need to change the mods files with winrar; overwrite the bootflow.gfx in that,(i think it will be in nexus mod file GLOBAL folder) rehash the files and add the hash and the size on index.js in htdocs folder, then when you are relaunch the game the mod manager will download the new bootlogo.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I was not aware that you dont know how mods works... sooo ....  All files in the mods are representing the exact structure like the client... so if you are replacing a file in for example GLOBAL folder it will overwrite the files in the global folder, and restores when you are quit the game... you can replace any file with this method inside the client... all you need to do is edit the mods files itself. You can use as many mods files as you want(it is recommended so if you are changing a tiny file the people on your server are not requied to download the whole modpack again only the smaller portion for example the globals folder or sound or gfx or cars whatever you are replacing...) So in your case:

You need to change the mods files with winrar; overwrite the bootflow.gfx in that,(i think it will be in nexus mod file GLOBAL folder) rehash the files(uSE TOTAL COMMANDER crc chacker, SHA1 will be needed) and add the hash and the size on index.js in htdocs folder at the appropriate lines(search what mod file you edited and edit that lines), then when you are relaunch the game the mod manager will download the new bootlogo.

**Comment by janmarinka** [comment]
Yesyes i know that, but yours isnt in a mod, its in ur launcher. And i cant seem to get it to extract. Oh well. I just found a solution, hopefully it will work.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
WHAT exactly is in my launcher?!?! The launcher not containing files from the client or from mods... all of my mod files are in the htdocs folder if you download my portable or CDN pack....

**Comment by janmarinka** [comment]
When its done

**Comment by janmarinka** [comment]
Yep its done

**Comment by 0P3N50URC3-F0R3V3R** [comment]
NO thanks only please do a tutorial on the news how to use it :D
