### ISSUE TITLE
Hello! Ban question, helpguide and more.

### ISSUE THREAD

**Issue by janmarinka** [0P3N50URC3-F0R3V3R/SBRW-COMPILED#3]
Hey,
I have a question. Do you know HOW to ban people? im on my admin account and i cant figure out how to ban anyone, or do other functions that admin can. Regarding your helpguide question, please provide me with your vps ip adress so I can customize the help code for you.

Best regards,
Jan

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Please provide a program that reads the domain from an ini file so i can read from there therefor i wont need to provide any adress to the public.(Check my custom launcher it reads the address from a file) As i said before i will not provide any personal info from my self so please provide here. There are admin commands, but you can ban people from Database also. (Never used ingame commands before, everyhthing i did)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I checked the source files, there are 4 distinc commands like:
Ban
kick
announce 
and an unknown one...

BUT: you need some kind of admin auth, in paramter table but IDK how to enable command line ingame... i mean i checked the source; it would be a / prefix for them but, IDK how to auth as admin so the commands are not working despite that my user table is  at isAdmin column is 1...

**Comment by janmarinka** [comment]
Ah. I see.

**Comment by janmarinka** [comment]
In terms of the helpguide, i'll try to probide that as it'd be easier.
