### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by AthallahDzaki** [0P3N50URC3-F0R3V3R/SBRW-COMPILED#4]
Source Code?

**Comment by AthallahDzaki** [comment]
Maybe someday someone will be able to help you develop this project

**Comment by 0P3N50URC3-F0R3V3R** [comment]
IF you would be so kind and take the time to read the readme file for the project, you would see that there is a link at the bottom of the tutorial for the source code. I wont need to provide since it is here in github. :D have fun.
