### ISSUE TITLE
bom-all from thorntail is end of life

### ISSUE THREAD

**Issue by AthallahDzaki** [0P3N50URC3-F0R3V3R/SBRW-COMPILED#5]
bom-all from thorntail is end of the life, so how i can compile code with Wilfly? The tutorial is Outdate

**Comment by 0P3N50URC3-F0R3V3R** [comment]
You dont need wildfly... I wrote you an information about the SDK with preconfigured VM in the other thread. Check relases descripion there is a VM to download.... get oracle virtual box, that has the requires parts to compile offline.
