### ISSUE TITLE
> 3k errors when starting the core

### ISSUE THREAD

**Issue by xZonda** [0P3N50URC3-F0R3V3R/SBRW-COMPILED#7]
[errorlog.txt](https://github.com/0P3N50URC3-F0R3V3R/SBRW-COMPILED/files/9603425/errorlog.txt)
I've asked leo, used several different compiled cores and compiled them myself and i still get this shitlong error list, i have no idea what causes it, i've tried following this and berkay's guide step by step and it still happens, any idea of what could it be?

**Comment by 0P3N50URC3-F0R3V3R** [comment]
That is because that tutorial is outdated, this is a compled version issue tracker, if you have questions about Berklay's source for compiling, ask there.
